name: Test actions

on:
  push:
    branches:
      - "*"

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run node tests
        run: .github/workflows/npm.sh test
